apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstore
  namespace: store
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webstore
  template:
    metadata:
      labels:
        app: webstore
    spec:
      containers:
        - name: webstore
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: webstore
  namespace: store
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: {{ .Values.service.port }}
  selector:
    app: webstore
