all:
  vars:
    ansible_user: "{{ auser }}"
    ansible_ssh_private_key_file: "{{ assh_private_key:file }}"
    ansible_become: true
    ansible_become_method: sudo

  children:
    k3s_cluster:
      children:
        k3s_server:
          hosts:
            master1:
              ansible_host: "{{ master1_ip }}"
              node_ip: "{{ master1_ip }}"
        k3s_agent:
          hosts:
            worker1:
              ansible_host: "{{ worker1_ip }}"
              node_ip: "{{ worker1_ip }}"
