all:
  vars:
    ansible_user: "{{ auser | default('ubuntu') }}"
    ansible_ssh_private_key_file: "{{ assh_private_key_file | default('.ssh/k3s-homelab') }}"
    ansible_become: true
    ansible_become_method: sudo

  children:
    k3s_cluster:
      children:
        k3s_server:
          hosts:
            master1:
              ansible_host: "{{ master1_ip | default('192.168.1.10') }}"
              node_ip: "{{ master1_ip | default('192.168.1.10') }}"
        k3s_agent:
          hosts:
            worker1:
              ansible_host: "{{ worker1_ip | default('192.168.1.11') }}"
              node_ip: "{{ worker1_ip | default('192.168.1.11') }}"
