apiVersion: v1
kind: Namespace
metadata:
  name: games
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      initContainers:
        - name: init-whitelist
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              cat > /data/whitelist.json << 'JSON'
              [{"uuid":"b5d7980e-1dd9-3dfc-8176-b327d09c87e4","name":"nuvhandra"}]
              JSON
              cat > /data/ops.json << 'JSON'
              [{"uuid":"b5d7980e-1dd9-3dfc-8176-b327d09c87e4","name":"nuvhandra","level":4,"bypassesPlayerLimit":false}]
              JSON
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: MEMORY
              value: "2G"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: ENABLE_WHITELIST
              value: "TRUE"
          ports:
            - containerPort: 25565
              name: minecraft
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: games
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: minecraft
  selector:
    app: minecraft-server
