- name: Restart SSH service
  service:
    name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    state: restarted

- name: Restart systemd-logind
  service:
    name: systemd-logind
    state: restarted

- name: Update GRUB
  command: update-grub
