apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
data:
  # This map will hold all files in .config
  {{- range $path, $bytes := .Files.Glob "files/.config/**" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}
