# Global Users Definition
users:
  - name: nuvhandra
    groups: sudo
    ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJU+FjS8lgZq/F8Q4n5Kz33kdrKLhGXZ1L5brkZXxbCa atrahasis@polaris"

# K3s Configuration
k3s_server_args: ""
k3s_token: "super-secret-k3s-token-12345"
